const canvas=document.getElementById('field');const ctx=canvas.getContext('2d');const world=document.getElementById('world');const presence=document.getElementById('presence');const conversation=document.getElementById('conversation');const form=document.getElementById('composer');const input=document.getElementById('input');const clock=document.getElementById('clock');const voice=document.getElementById('voice');const identity=document.getElementById('identity');const particles=[];let dpr=1,w=0,h=0,px=.5,py=.5,energy=0,targetEnergy=0,active=false;
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);particles.length=0;const n=Math.min(220,Math.max(90,Math.floor(w*h/6500)));for(let i=0;i<n;i++){const angle=Math.random()*Math.PI*2;const radius=Math.pow(Math.random(),.65);particles.push({x:Math.random(),y:Math.random(),z:radius,r:Math.random()*1.25+.2,a:Math.random()*.42+.05,p:Math.random()*6.28,v:(Math.random()-.5)*.0005});}}
function draw(t=0){ctx.clearRect(0,0,w,h);const cx=w*(.5+(px-.5)*.035),cy=h*(.51+(py-.5)*.025),min=Math.min(w,h);const bg=ctx.createRadialGradient(cx,cy,0,cx,cy,min*.48);bg.addColorStop(0,`rgba(64,170,218,${.055+energy*.04})`);bg.addColorStop(.3,'rgba(28,89,128,.018)');bg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
for(const p of particles){p.p+=p.v*16;const drift=Math.sin(t*.00018+p.p)*12*(1-p.z);const x=p.x*w+drift+(px-.5)*12*p.z;const y=p.y*h+Math.cos(t*.00015+p.p)*9*(1-p.z)+(py-.5)*8*p.z;const a=p.a*(.58+.42*Math.sin(p.p*1.7+t*.0006));ctx.beginPath();ctx.arc(x,y,p.r*(.65+p.z),0,Math.PI*2);ctx.fillStyle=`rgba(151,221,245,${Math.max(.015,a)})`;ctx.fill();}
const beam=ctx.createRadialGradient(cx,cy,0,cx,cy,90+energy*100);beam.addColorStop(0,`rgba(123,231,255,${.11+energy*.18})`);beam.addColorStop(.3,`rgba(96,188,229,${.035+energy*.06})`);beam.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=beam;ctx.beginPath();ctx.arc(cx,cy,140,0,Math.PI*2);ctx.fill();energy+=(targetEnergy-energy)*.08;targetEnergy*=.94;requestAnimationFrame(draw)}
function tick(){clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}tick();setInterval(tick,1000);resize();addEventListener('resize',resize);
addEventListener('pointermove',e=>{px=e.clientX/w;py=e.clientY/h;presence.style.transform=`translate(-50%,-50%) translate(${(px-.5)*18}px,${(py-.5)*12}px)`;targetEnergy=.35});addEventListener('pointerdown',()=>{targetEnergy=1.1;active=true;world.classList.add('awake');setTimeout(()=>{targetEnergy=.3},700)});
function addMessage(text,user=false){const el=document.createElement('div');el.className='msg'+(user?' user':'');el.innerHTML=`<small>${user?'YOU':'WULAN'}</small><p></p>`;el.querySelector('p').textContent=text;conversation.appendChild(el);while(conversation.children.length>4)conversation.removeChild(conversation.firstChild);targetEnergy=user?1.25:.7;}
const replies=["I’m here.","I’m with you. Tell me what you want to build.","I’m listening. What should we connect?","Got it. Let’s make it real."];
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text,true);input.value='';setTimeout(()=>addMessage(replies[Math.floor(Math.random()*replies.length)]),380)});
voice.addEventListener('click',()=>{voice.classList.toggle('active');input.focus();input.placeholder=voice.classList.contains('active')?'Listening…':'Talk to Wulan';targetEnergy=voice.classList.contains('active')?1:.25});
identity.addEventListener('click',()=>{targetEnergy=1.2;setTimeout(()=>targetEnergy=.35,900)});
document.querySelectorAll('.rail-item').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.rail-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');targetEnergy=.8}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){input.blur();voice.classList.remove('active');input.placeholder='Talk to Wulan'}if(e.key===' '&&document.activeElement!==input){targetEnergy=1.1}});draw();
