import { createDefaultWulanCore } from './wulan/core/manifest.js';
import { WULAN_EVENTS } from './wulan/core/event-bus.js';

(() => {
  const $ = (s) => document.querySelector(s);
  const canvas = $('#nova-canvas');
  const ctx = canvas?.getContext('2d');
  const input = $('#nova-input');
  const composer = $('#composer');
  const messages = $('#messages');
  const voice = $('#voice');
  const memoryCountEl = $('#memory-count');
  const memoryHint = $('#memory-hint');
  const providerHint = $('#provider-hint');
  const providerState = $('#provider-state');
  const clock = $('#clock');

  let core;
  try {
    core = window.WULAN_CORE || createDefaultWulanCore();
    window.WULAN_CORE = core;
  } catch (error) {
    console.error('[Wulan] core boot construction failed', error);
    core = null;
  }

  const style = document.createElement('style');
  style.textContent = `
    :root{--w-bg:#03070d;--w-line:rgba(148,213,240,.16);--w-cyan:#79e8ff;--w-violet:#a98bff;--w-mint:#70e5b4;--w-text:#e8f4fb}
    html,body{background:#02060b!important;color:var(--w-text);overflow:hidden}
    body{background:radial-gradient(ellipse at 50% 45%,rgba(15,42,66,.52) 0%,rgba(4,12,21,.82) 34%,#02060b 76%)!important}.grain{opacity:.16!important}
    .wulan-world{height:100dvh!important;min-height:640px;overflow:hidden!important}
    .w-top{top:22px!important;left:30px!important;right:30px!important;height:48px!important}.w-mark{width:40px!important;height:40px!important;border-radius:13px!important;background:linear-gradient(145deg,rgba(121,232,255,.12),rgba(121,232,255,.025))!important;box-shadow:0 0 35px rgba(121,232,255,.12),inset 0 0 20px rgba(121,232,255,.035)!important;font-size:14px!important}.w-id{gap:13px!important}.w-id strong{font-size:14px!important;letter-spacing:.3em!important}.w-id small{font-size:7px!important;color:#71869b!important}.w-online{font-size:7px!important;color:#6d8298!important}.w-online i{width:6px!important;height:6px!important}
    .w-rail{left:30px!important;top:125px!important;bottom:34px!important;width:118px!important;gap:8px!important}.w-kicker{font-size:7px!important;color:#52687d!important;padding:6px 10px 16px!important}.w-nav,.w-neural{padding:11px 10px!important;border-radius:10px!important}.w-nav b,.w-neural b{font-size:9px!important;letter-spacing:.16em!important}.w-nav small,.w-neural small{font-size:7px!important;color:#5b7085!important}.w-nav span,.w-neural span{font-size:7px!important}
    .w-panel{width:276px!important;padding:18px 19px!important;border-radius:18px!important;background:linear-gradient(145deg,rgba(9,18,30,.82),rgba(3,8,15,.58))!important;border-color:rgba(148,213,240,.15)!important;box-shadow:0 30px 100px rgba(0,0,0,.36),inset 0 1px rgba(255,255,255,.035)!important}.w-left{left:170px!important;top:125px!important}.w-right{right:30px!important;top:125px!important;width:286px!important}.w-head{font-size:7px!important;margin-bottom:13px!important}.w-row{padding:10px 0!important}.w-row b,.w-tool b{font-size:9px!important}.w-row small,.w-tool small{font-size:7px!important}.w-row em,.w-tool em{font-size:6px!important}.w-dot{width:6px!important;height:6px!important}.w-stats strong{font-size:21px!important}.w-stats small{font-size:6px!important}.w-glyph{width:28px!important;height:28px!important}
    .w-stage{inset:80px 350px 125px 350px!important;z-index:5!important}.w-title{top:12%!important}.w-title span{font-size:7px!important;letter-spacing:.5em!important}.w-title h1{font-size:clamp(40px,4.6vw,72px)!important;margin:13px 0 8px!important}.w-title p{font-size:7px!important;color:#657b91!important}.w-caption{bottom:5%!important;font-size:6px!important}
    .w-chat{width:min(760px,calc(100% - 720px))!important;min-width:520px;bottom:28px!important;z-index:100!important}.w-chat .messages{max-height:150px!important;gap:8px!important;margin-bottom:10px!important;padding:0 8px!important}.w-chat .message{max-width:82%!important;padding:10px 13px!important;border-radius:14px!important;background:rgba(7,15,24,.9)!important;border-color:rgba(148,213,240,.14)!important;box-shadow:0 12px 40px rgba(0,0,0,.18)!important}.w-chat .message.user{background:linear-gradient(135deg,rgba(43,120,151,.24),rgba(26,70,91,.12))!important;border-color:rgba(121,232,255,.25)!important}.w-chat .message-name{font-size:6px!important;margin-bottom:4px!important}.w-chat .message p{font-size:12px!important;line-height:1.45!important}.w-chat .composer{height:62px!important;border:1px solid rgba(148,213,240,.2)!important;border-radius:18px!important;background:linear-gradient(145deg,rgba(8,17,28,.92),rgba(4,10,17,.8))!important;box-shadow:0 20px 80px rgba(0,0,0,.45),0 0 45px rgba(121,232,255,.045),inset 0 1px rgba(255,255,255,.04)!important;padding:6px!important}.w-chat .composer input{font-size:14px!important;color:#e8f4fb!important}.w-chat .composer input::placeholder{color:#637a90!important}.w-chat .composer .voice,.w-chat .composer .send{width:48px!important;height:48px!important;border-radius:14px!important}.w-chat .composer .send{background:linear-gradient(145deg,rgba(121,232,255,.16),rgba(121,232,255,.05))!important;border-color:rgba(121,232,255,.25)!important}.w-chat .hint{display:none!important}.runtime-hidden{display:none!important}
    .wulan-ambient{position:absolute;inset:0;z-index:1;pointer-events:none;overflow:hidden}.wulan-ambient:before{content:"";position:absolute;left:50%;top:51%;width:min(68vw,1050px);height:min(48vw,650px);transform:translate(-50%,-50%);border:1px solid rgba(121,232,255,.08);border-radius:50%;box-shadow:0 0 90px rgba(52,149,204,.06),inset 0 0 90px rgba(52,149,204,.025)}.wulan-ambient:after{content:"";position:absolute;left:50%;top:51%;width:min(48vw,740px);height:min(34vw,500px);transform:translate(-50%,-50%);border:1px solid rgba(169,139,255,.055);border-radius:50%;animation:wulanBreath 8s ease-in-out infinite}.wulan-scan{position:absolute;left:50%;top:51%;width:min(52vw,820px);height:1px;transform:translate(-50%,-50%);background:linear-gradient(90deg,transparent,rgba(121,232,255,.15),transparent);filter:blur(.2px);animation:wulanScan 7s ease-in-out infinite}@keyframes wulanBreath{0%,100%{transform:translate(-50%,-50%) scale(.98);opacity:.45}50%{transform:translate(-50%,-50%) scale(1.03);opacity:1}}@keyframes wulanScan{0%,100%{opacity:.15;transform:translate(-50%,-50%) scaleX(.7)}50%{opacity:.65;transform:translate(-50%,-50%) scaleX(1)}}
    @media(max-width:1250px){.w-panel{display:none!important}.w-rail{left:22px!important}.w-stage{inset:80px 80px 125px!important}.w-chat{width:min(760px,calc(100% - 170px))!important;min-width:0!important}}@media(max-width:720px){.w-top{left:14px!important;right:14px!important}.w-rail{display:none!important}.w-stage{inset:70px 12px 145px!important}.w-title{top:9%!important}.w-title h1{font-size:38px!important}.w-chat{width:calc(100% - 20px)!important;bottom:12px!important}.w-chat .message p{font-size:11px!important}.wulan-ambient:before{width:120vw;height:75vw}.wulan-ambient:after{width:90vw;height:55vw}}
  `;
  document.head.appendChild(style);
  const ambient=document.createElement('div');ambient.className='wulan-ambient';ambient.innerHTML='<div class="wulan-scan"></div>';$('.wulan-world')?.prepend(ambient);

  let dpr=1,w=0,h=0,time=0;const nodes=Array.from({length:54},(_,i)=>({a:(Math.PI*2*i)/54+Math.random()*.08,r:.35+Math.random()*.62,s:.08+Math.random()*.24,p:Math.random()*Math.PI*2}));const pointer={x:0,y:0,active:false};
  function resize(){if(!canvas||!ctx)return;dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);pointer.x=w/2;pointer.y=h/2}addEventListener('resize',resize);resize();
  function drawField(){if(!ctx)return;ctx.clearRect(0,0,w,h);const cx=w*.5+Math.sin(time*.12)*w*.006,cy=h*.51+Math.cos(time*.1)*h*.005,scale=Math.min(w,h),pulse=1+Math.sin(time*.75)*.018;const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,scale*.44);glow.addColorStop(0,'rgba(79,180,235,.09)');glow.addColorStop(.3,'rgba(67,111,191,.045)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);for(let ring=0;ring<6;ring++){ctx.beginPath();const rx=scale*(.12+ring*.055)*pulse,ry=scale*(.075+ring*.036)*pulse;for(let i=0;i<=180;i++){const a=i/180*Math.PI*2,wob=Math.sin(a*(3+ring)+time*(.2+ring*.025))*.008*scale,x=cx+Math.cos(a)*(rx+wob),y=cy+Math.sin(a)*(ry+wob*.6);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=`rgba(105,205,255,${.035-ring*.003})`;ctx.lineWidth=ring===0?1.1:.7;ctx.stroke()}nodes.forEach((n,i)=>{n.a+=.0007*n.s;const rr=scale*(.18+n.r*.24),x=cx+Math.cos(n.a)*rr,y=cy+Math.sin(n.a)*rr*.68,near=pointer.active?Math.max(0,1-Math.hypot(x-pointer.x,y-pointer.y)/(scale*.22)):0,alpha=.10+near*.38+(Math.sin(time*.9+n.p)+1)*.035;ctx.beginPath();ctx.arc(x,y,1.2+near*2.2,0,Math.PI*2);ctx.fillStyle=`rgba(168,235,255,${alpha})`;ctx.fill();if(i%5===0){ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.strokeStyle=`rgba(121,232,255,${.012+near*.055})`;ctx.lineWidth=.5;ctx.stroke()}});requestAnimationFrame(drawField);time+=.012}drawField();

  function addMessage(who,text){if(!messages)return;const el=document.createElement('div');el.className=`message ${who}`;const name=document.createElement('span');name.className='message-name';name.textContent=who==='user'?'YOU':'WULAN';const p=document.createElement('p');p.textContent=text;el.append(name,p);messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
  function memoryCount(){try{return core?.memory?.list?.({limit:5000})?.length||0}catch{return 0}}function save(){try{core?.persistence?.saveCore?.(core)}catch{}}
  function localReply(text){const s=text.toLowerCase();if(/^(hi|hey|hello|yo|bro)\b/.test(s))return "Hey. I'm here. What are we building?";if(/who are you|what are you/.test(s))return "I'm Wulan — the personal intelligence layer we're building around your tools, memory and work.";if(/memory|remember/.test(s))return memoryCount()?`I have ${memoryCount()} memories stored locally.`:"Memory is ready. Tell me what you want me to remember.";if(/sentinel/.test(s))return "Sentinel is connected to the world model. I can work with its registered capabilities when they're available.";if(/strategy.?lab/.test(s))return "Strategy Lab is registered in my world model. We can build on it from here.";return `I heard you: “${text}”. My local runtime is online.`}
  async function withTimeout(promise,ms){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('AI response timeout')),ms)})])}finally{clearTimeout(timer)}}
  async function sendMessage(raw){const text=String(raw||'').trim();if(!text||!input)return;input.value='';addMessage('user',text);try{core?.events?.emit?.(WULAN_EVENTS.USER_MESSAGE,{text})}catch{}try{core?.remember?.({content:text,type:'experience',source:'conversation',importance:.35,tags:['conversation','session']});save()}catch{}if(memoryCountEl)memoryCountEl.textContent=String(memoryCount());if(memoryHint)memoryHint.textContent=`memory · ${memoryCount()} stored`;let reply;try{const history=[...messages.querySelectorAll('.message')].slice(-12).map(el=>({role:el.classList.contains('user')?'user':'assistant',content:el.querySelector('p')?.textContent||''}));const generated=core?.ai?.generate?await withTimeout(core.ai.generate({messages:history,system:'You are Wulan, a private personal AI OS. Speak naturally, confidently and concisely. Never expose internal chain-of-thought or internal state labels. If you cannot perform an action, say so plainly and offer the next useful step.'}),4000):null;reply=typeof generated==='string'?generated:(generated?.text||generated?.content||null)}catch(error){console.warn('[Wulan] provider unavailable; using local response',error);reply=localReply(text)}addMessage('wulan',reply||localReply(text));try{core?.recordFeedback?.({outcome:'accepted',context:text,candidatePreference:null,source:'conversation',confidence:.35});save()}catch{}input.focus()}
  composer?.addEventListener('submit',e=>{e.preventDefault();sendMessage(input?.value)});$('#nova-send')?.addEventListener('click',e=>{e.preventDefault();sendMessage(input?.value)});input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer?.requestSubmit?.()}});
  voice?.addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){addMessage('wulan','Voice input is not available in this browser. Text is ready.');return}const rec=new SR();rec.lang=navigator.language||'en-IN';rec.interimResults=false;rec.maxAlternatives=1;rec.onresult=e=>sendMessage(e.results?.[0]?.[0]?.transcript||'');rec.onerror=()=>{};try{rec.start()}catch{}});
  document.querySelectorAll('.w-nav').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action;document.querySelectorAll('.w-nav').forEach(n=>n.classList.toggle('active',n===btn));const lines={memory:`Memory is ready. ${memoryCount()} memories are stored locally.`,agents:`${core?.state?.agents?.size||0} agents are registered.`,projects:`${core?.world?.listProjects?.().length||0} projects are present.`,systems:`${core?.state?.integrations?.size||0} integrations are registered.`};addMessage('wulan',lines[a]||'Done.') }));
  document.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.active=true});document.addEventListener('pointerleave',()=>pointer.active=false);
  async function boot(){if(!core){if(providerState)providerState.textContent='LOCAL';if(providerHint)providerHint.textContent='LOCAL MODE';addMessage('wulan','I’m online in local mode. The core could not initialize fully.');return}try{core.events?.on?.(WULAN_EVENTS.SYSTEM_READY,()=>{const providers=core.ai?.listProviders?.()||[];if(providerState)providerState.textContent=providers.length?'ONLINE':'LOCAL';if(providerHint)providerHint.textContent=providers.length?'AI GATEWAY · ONLINE':'LOCAL CORE · ONLINE'});await Promise.resolve(core.boot?.())}catch(error){console.error('[Wulan] boot error',error);if(providerState)providerState.textContent='LOCAL';if(providerHint)providerHint.textContent='LOCAL CORE · ONLINE'}if(memoryCountEl)memoryCountEl.textContent=String(memoryCount());if(memoryHint)memoryHint.textContent=memoryCount()?`memory · ${memoryCount()} stored`:'memory · ready';if(providerState&&core.ai?.listProviders)providerState.textContent=(core.ai.listProviders()||[]).length?'ONLINE':'LOCAL'}
  boot();if(clock){const tick=()=>clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});tick();setInterval(tick,1000)}
})();
