// Wulan AI Gateway — provider-neutral model boundary.
// Providers are adapters. A bounded local fallback keeps the interface alive
// during provider outages without pretending an external model answered.
export class WulanAIGateway {
  constructor(){this.providers=new Map();this.defaultProvider=null;this.lastError=null;this.lastProvider=null;this.lastSuccessAt=null;this.lastCallAt=null;}
  registerProvider({id,name,generate,embed,capabilities=[]}){if(!id||!name||typeof generate!=='function')throw new TypeError('AI provider requires id, name and generate()');if(this.providers.has(id))throw new Error(`AI provider already registered: ${id}`);const provider={id,name,generate,embed:typeof embed==='function'?embed:null,capabilities:[...new Set(capabilities)]};this.providers.set(id,provider);if(!this.defaultProvider)this.defaultProvider=id;return provider;}
  setDefaultProvider(id){if(!this.providers.has(id))throw new Error(`Unknown provider: ${id}`);this.defaultProvider=id;}
  listProviders(){return [...this.providers.values()].map(({generate,embed,...metadata})=>({...metadata,embedding:Boolean(embed)}));}
  status(){return{provider:this.defaultProvider,available:Boolean(this.defaultProvider&&this.providers.has(this.defaultProvider)),lastProvider:this.lastProvider,lastSuccessAt:this.lastSuccessAt,lastError:this.lastError,lastCallAt:this.lastCallAt};}
  async generate(request={}, {providerId}={}){const id=providerId??this.defaultProvider;const provider=this.providers.get(id);if(!provider)throw new Error('No AI provider is configured');this.lastCallAt=new Date().toISOString();try{const result=await provider.generate(request);this.lastProvider=id;this.lastSuccessAt=new Date().toISOString();this.lastError=null;return result;}catch(error){this.lastProvider=id;this.lastError=String(error?.message||error);if(request?.allowLocalFallback!==false)return localFallback(request,this.lastError);throw error;}}
  async embed(input,{providerId}={}){const id=providerId??this.defaultProvider;const provider=this.providers.get(id);if(!provider)throw new Error('No AI provider is configured');if(!provider.embed)throw new Error(`Provider ${id} does not expose embeddings`);return provider.embed(input);}
}
function localFallback(request,reason){const messages=Array.isArray(request?.messages)?request.messages:[];const last=[...messages].reverse().find(m=>String(m?.role||'').toLowerCase()==='user');const text=String(last?.content??last?.text??'').trim();const s=text.toLowerCase();const quota=/429|quota|rate.?limit|resource.?exhausted|503|timeout/i.test(reason||'');if(/^(hi|hey|hello|yo|bro)\b/.test(s))return"Hey. I'm here. What are we building?";if(/who are you|what are you/.test(s))return"I'm Wulan — the local intelligence layer around your memory, neural substrate, agents and connected tools.";if(/what do you remember|memory/.test(s))return"Your local memory layer is online. I can store experiences, connect them to concepts, and use those relationships when they become relevant.";if(/neural|neuron|network|learning/.test(s))return"The neural substrate is live locally. Your messages create concepts and memories, activate related neurons, and reinforce relationships through feedback.";if(/what are those|what is this|what's this/.test(s))return"Those are live pieces of Wulan's internal graph — concepts, memories and agents linked by weighted synapses. Open Neural Field to inspect their real state.";if(/sentinel/.test(s))return"Sentinel is registered as a connected system. Its live state can become part of Wulan's working context when the integration is available.";if(/github/.test(s))return"GitHub is registered as a development integration and can become part of Wulan's tool layer when authorized.";if(/edgelab|edge lab/.test(s))return"EdgeLab is registered as a research integration and can become part of Wulan's working context.";if(quota)return"I'm still here. Gemini is temporarily unavailable, so I'm using Wulan's local layer instead of pretending the model answered.";return`I heard you: “${text}”. My local core is online; the external model is unavailable right now, so I won't fake an answer I don't have.`;}