const safeJson=text=>{try{return JSON.parse(text)}catch{const match=String(text??'').match(/\{[\s\S]*\}/);if(!match)return null;try{return JSON.parse(match[0])}catch{return null}}};
const id=()=>`cog_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;

export class WulanCognitionLoop{
 constructor(core,{maxMemoryHits=8,maxSemanticHits=5,maxSteps=6,providerId}={}){if(!core)throw new TypeError('Cognition loop requires Wulan core');this.core=core;this.maxMemoryHits=maxMemoryHits;this.maxSemanticHits=maxSemanticHits;this.maxSteps=maxSteps;this.providerId=providerId;this.runs=[];this.maxRuns=100;}
 async run(input,{execute=true,providerId=this.providerId,context={}}={}){
  const run={id:id(),input:String(input??'').trim(),startedAt:new Date().toISOString(),status:'running',steps:[],context:{...context}};
  if(!run.input)throw new TypeError('Cognition input is required');this.runs.push(run);if(this.runs.length>this.maxRuns)this.runs.shift();
  const emit=(type,payload)=>this.core.events.emit(type,{runId:run.id,...payload},{correlationId:run.id});
  emit('cognition.started',{input:run.input});
  try{
   const memory=this.core.searchMemory(run.input,{limit:this.maxMemoryHits});let semantic=[];try{semantic=await this.core.searchSemanticMemory(run.input,{limit:this.maxSemanticHits,providerId});}catch{}
   const neural=this.core.neural.predict(run.input);const contextBlock=this.#context(memory,semantic,neural);run.steps.push({stage:'perceive',memory:memory.length,semantic:semantic.length,neural:neural.trace.length});emit('cognition.perceived',{memory:memory.length,semantic:semantic.length,neural:neural.trace.length});
   const plan=await this.#plan(run.input,contextBlock,providerId);run.plan=plan;run.steps.push({stage:'plan',plan});emit('cognition.planned',{plan});
   if(!execute||!plan.actions.length){run.status='planned';run.finishedAt=new Date().toISOString();run.answer=plan.answer??null;emit('cognition.completed',{status:run.status,answer:run.answer});return run;}
   const results=[];for(const action of plan.actions.slice(0,this.maxSteps)){if(!action?.capabilityId)continue;const capability=this.core.capabilities.get(action.capabilityId);if(!capability){results.push({capabilityId:action.capabilityId,status:'blocked',error:'CAPABILITY_NOT_REGISTERED'});continue;}if(capability.requiresApproval&&!context.approvedCapabilities?.includes(action.capabilityId)){results.push({capabilityId:action.capabilityId,status:'blocked',error:'APPROVAL_REQUIRED'});continue;}emit('cognition.action_started',{capabilityId:action.capabilityId,input:action.input??{}});try{const result=await this.core.invokeCapability(action.capabilityId,action.input??{},{correlationId:run.id,cognitionRun:run.id});results.push({capabilityId:action.capabilityId,status:'success',result});emit('cognition.action_finished',{capabilityId:action.capabilityId,status:'success'});}catch(error){results.push({capabilityId:action.capabilityId,status:'failed',error:String(error?.message||error)});emit('cognition.action_finished',{capabilityId:action.capabilityId,status:'failed',error:String(error?.message||error)});}}
   run.results=results;run.answer=await this.#interpret(run.input,run.plan,results,providerId);run.status=results.some(r=>r.status==='failed')?'partial':'completed';await this.#learn(run);run.finishedAt=new Date().toISOString();emit('cognition.completed',{status:run.status,results:results.map(({capabilityId,status,error})=>({capabilityId,status,error})),answer:run.answer});return run;
  }catch(error){run.status='failed';run.error=String(error?.message||error);run.finishedAt=new Date().toISOString();return run;}
 }
 #context(memory,semantic,neural){const lexical=memory.map(({memory:entry,score})=>({id:entry.id,content:entry.content,type:entry.type,score,source:'lexical'}));const semanticHits=semantic.map(hit=>({id:hit.memory?.id,content:hit.memory?.content,type:hit.memory?.type,score:hit.score,source:'semantic'}));const merged=[...semanticHits,...lexical].filter(x=>x.content);const unique=new Map();for(const item of merged){const previous=unique.get(item.id);if(!previous||item.score>previous.score)unique.set(item.id,item);}return JSON.stringify({memories:[...unique.values()].sort((a,b)=>b.score-a.score).slice(0,10),neural:neural.trace.slice(0,14)});}
 async #plan(input,context,providerId){const system=`You are the planning layer inside Wulan. Return ONLY valid JSON. Never invent capability IDs. Schema: {"intent":string,"answer":string,"actions":[{"capabilityId":string,"input":object}],"learningSignal":"accepted|corrected|rejected|none"}. Registered capabilities: ${JSON.stringify(this.core.capabilities.list())}`;try{const text=await this.core.ai.generate({messages:[{role:'user',content:`User request:\n${input}\n\nRetrieved context:\n${context}`}],system,source:'cognition-plan'},{providerId});const parsed=safeJson(text);if(parsed){const allowed=new Set(this.core.capabilities.list().map(c=>c.id));const actions=Array.isArray(parsed.actions)?parsed.actions.filter(a=>allowed.has(a?.capabilityId)).slice(0,this.maxSteps).map(a=>({capabilityId:a.capabilityId,input:a.input&&typeof a.input==='object'?a.input:{}})):[];if(actions.length||!this.#hasCapabilityIntent(input))return{intent:String(parsed.intent??'respond'),answer:String(parsed.answer??''),actions,learningSignal:['accepted','corrected','rejected','none'].includes(parsed.learningSignal)?parsed.learningSignal:'none'};}}catch{}return this.#deterministicPlan(input);}
 #hasCapabilityIntent(input){return /\b(strategy\s*lab|sentinel|github|system status|memory|remember|neural|agents?|projects?|integrations?)\b/i.test(String(input));}
 #deterministicPlan(input){const text=String(input).trim(),s=text.toLowerCase(),caps=new Set(this.core.capabilities.list().map(c=>c.id));const action=(capabilityId,input={})=>caps.has(capabilityId)?[{capabilityId,input}]:[];if(/strategy\s*lab|strategy labs/.test(s))return{intent:'inspect_strategy_lab',answer:'I’ll inspect Strategy Lab and bring back the live repository state.',actions:action('strategy-lab.inspect',{repo:'fakej3/strategy-lab'}),learningSignal:'none'};if(/sentinel/.test(s))return{intent:'inspect_sentinel',answer:'I’ll inspect Sentinel and bring back the live repository/deployment state.',actions:action('sentinel.inspect',{repo:'fakej3/Sentinel',branch:'main'}),learningSignal:'none'};if(/github/.test(s))return{intent:'inspect_github',answer:'I’ll inspect the Nova GitHub repository.',actions:action('github.inspect',{owner:'fakej3',repo:'nova',ref:'master'}),learningSignal:'none'};if(/system\s*status|status of wulan|how is wulan|is wulan/.test(s))return{intent:'system_status',answer:'I’ll check Wulan’s live runtime status.',actions:action('system.status'),learningSignal:'none'};if(/remember|save this|don’t forget|do not forget/.test(s))return{intent:'remember',answer:'I’ll store that as a durable memory.',actions:action('memory.remember',{content:text,type:'instruction',importance:.85,tags:['explicit-memory']}),learningSignal:'none'};return{intent:'respond',answer:'I’m here. The local cognition core is online, but I don’t have a registered action for that request yet.',actions:[],learningSignal:'none'};}
 async #interpret(input,plan,results,providerId){const successful=results.filter(r=>r.status==='success');const failed=results.filter(r=>r.status!=='success');if(!successful.length)return failed.length?`I couldn't complete that action: ${failed.map(r=>r.error||r.capabilityId).join(', ')}.`:plan.answer||'Done.';const compact=successful.map(r=>({capabilityId:r.capabilityId,result:r.result}));try{const text=await this.core.ai.generate({messages:[{role:'user',content:`User request:\n${input}\n\nPlanned intent:\n${plan.intent}\n\nCapability results:\n${JSON.stringify(compact)}`}],system:'You are Wulan’s response layer. Explain what the executed capability results actually show. Do not invent facts, do not say an action happened unless the result supports it, and do not expose internal JSON. Be concise but useful.',source:'cognition-interpret',allowLocalFallback:false},{providerId});if(String(text??'').trim())return String(text).trim();}catch{}return this.#localInterpret(input,compact,failed);}
 #localInterpret(input,results,failed){const r=results[0]?.result??{};if(results[0]?.capabilityId==='strategy-lab.inspect'){const files=Array.isArray(r.files)?r.files.length:0;return `Strategy Lab inspection completed. I found the live repository state${files?` and inspected ${files} selected file(s)`:''}. I can now use that result as working context.`;}if(results[0]?.capabilityId==='sentinel.inspect'){return 'Sentinel inspection completed. I have the live repository/deployment result available in this cognition run.';}if(results[0]?.capabilityId==='system.status'){return `Wulan runtime is ${r.status??'available'} with ${Array.isArray(r.agents)?r.agents.length:0} agent(s), ${Array.isArray(r.integrations)?r.integrations.length:0} integration(s), and ${Array.isArray(r.capabilities)?r.capabilities.length:0} registered capability(ies).`;}if(results[0]?.capabilityId==='memory.remember'){return 'Got it. I stored that as a durable Wulan memory.';}return failed.length?`${plan.answer||'The action completed, but part of the result could not be interpreted.'} ${failed.length} action(s) failed.`:(plan.answer||'Done.');}
 async #learn(run){const signal=run.plan?.learningSignal;if(signal&&signal!=='none'){try{this.core.recordFeedback({context:run.input,outcome:signal,candidatePreference:run.plan?.actions?.[0]?.capabilityId??'general',source:'cognition'});}catch{}}}
 recent(limit=20){return this.runs.slice(-limit).reverse();}
 stats(){return{runs:this.runs.length,completed:this.runs.filter(r=>r.status==='completed').length,partial:this.runs.filter(r=>r.status==='partial').length,failed:this.runs.filter(r=>r.status==='failed').length};}
}
