/**
 * Wulan Neural Substrate v3
 *
 * A small, inspectable associative learning system. It is not an LLM trainer.
 * The network learns relationships between concepts, memories and agents from
 * real Wulan events. Learning is temporal, signed and bounded.
 */
const STOP=new Set(['about','after','again','also','and','are','been','being','but','can','could','did','does','for','from','have','how','into','just','like','more','most','not','now','only','our','that','their','then','there','these','they','this','was','what','when','where','which','with','would','you','your','wulan']);
const clamp=(n,min=0,max=1)=>Math.min(max,Math.max(min,Number(n)||0));
const normalize=value=>String(value??'').toLowerCase().replace(/[^a-z0-9_\- ]+/g,' ').replace(/\s+/g,' ').trim();
const terms=(text,limit=24)=>[...new Set(normalize(text).split(' ').filter(w=>w.length>=3&&!STOP.has(w)))].slice(0,limit);
const idFor=(type,key)=>`${type}:${normalize(key).replace(/\s+/g,'_').slice(0,80)}`;
const now=()=>new Date().toISOString();

export class WulanNeuralSubstrate{
 constructor({maxNeurons=1200,maxSynapses=5000,decayHalfLifeHours=168,learningRate=.12}={}){this.maxNeurons=maxNeurons;this.maxSynapses=maxSynapses;this.decayHalfLifeHours=decayHalfLifeHours;this.learningRate=learningRate;this.neurons=new Map();this.synapses=new Map();this.activations=[];this.updates=0;this.lastTrace=[];this.lastInput='';}
 ensureNeuron({id,label,type='concept',strength=.5,tags=[]}){if(!id)return null;const existing=this.neurons.get(id);if(existing){existing.strength=clamp(Math.max(existing.strength,strength));existing.tags=[...new Set([...(existing.tags??[]),...tags])].slice(0,24);existing.updatedAt=now();return existing;}const neuron={id,label:String(label??id),type,strength:clamp(strength),activation:0,visits:0,createdAt:now(),updatedAt:now(),lastActivatedAt:null,tags:[...new Set(tags)].slice(0,24)};this.neurons.set(id,neuron);this.trim();return neuron;}
 getNeuron(id){return this.neurons.get(id)??null;}
 adjustSynapse(source,target,delta=0,evidence=1){if(!source||!target||source===target)return null;const key=`${source}>${target}`;let edge=this.synapses.get(key);if(!edge){edge={id:key,source,target,weight:clamp(.35+delta,.02,.95),evidence:0,createdAt:now(),updatedAt:now()};this.synapses.set(key,edge);}else edge.weight=clamp(edge.weight+delta,.02,.95);edge.evidence=Math.max(0,edge.evidence+Math.abs(evidence));edge.updatedAt=now();this.updates+=1;this.trim();return edge;}
 connect(source,target,weight=.35,evidence=1){if(!source||!target||source===target)return null;const key=`${source}>${target}`;let edge=this.synapses.get(key);if(!edge){edge={id:key,source,target,weight:clamp(weight,.02,.95),evidence:Math.max(0,Number(evidence)||0),createdAt:now(),updatedAt:now()};this.synapses.set(key,edge);}else{edge.weight=clamp(weight,.02,.95);edge.evidence=Math.max(0,edge.evidence+Math.abs(evidence));edge.updatedAt=now();}this.updates+=1;this.trim();return edge;}
 ingestMemory(memory){if(!memory?.content)return null;const memoryNeuron=this.ensureNeuron({id:idFor('memory',memory.id),label:String(memory.content).slice(0,72),type:'memory',strength:memory.importance??.5,tags:memory.tags??[]});const concepts=terms(`${memory.content} ${(memory.tags??[]).join(' ')}`);for(let i=0;i<concepts.length;i++){const term=concepts[i],concept=this.ensureNeuron({id:idFor('concept',term),label:term,type:'concept',strength:.35,tags:['learned']});const weight=clamp((memory.confidence??.8)*(1-i*.025),.08,.9);this.connect(memoryNeuron.id,concept.id,weight,1);this.connect(concept.id,memoryNeuron.id,.18,1);}this.updates+=1;return memoryNeuron;}
 ingestFeedback(record){if(!record?.context)return null;const contextTerms=terms(record.context);const agent=record.candidatePreference||'general';const agentNeuron=this.ensureNeuron({id:idFor('agent',agent),label:agent,type:'agent',strength:.5,tags:['routing']});const outcome=record.outcome??'unknown';const delta=outcome==='accepted'?.12:outcome==='corrected'?.07:outcome==='rejected'?-.12:outcome==='explicit_preference'?.15:.02;agentNeuron.strength=clamp(agentNeuron.strength+delta);agentNeuron.visits+=1;agentNeuron.updatedAt=now();for(const term of contextTerms){const concept=this.ensureNeuron({id:idFor('concept',term),label:term,type:'concept',strength:.4,tags:['feedback']});const signed=Math.max(-.2,Math.min(.2,delta));this.adjustSynapse(concept.id,agentNeuron.id,signed,.5+Math.abs(signed)*5);this.adjustSynapse(agentNeuron.id,concept.id,signed*.7,.5+Math.abs(signed)*5);}if(record.correction)for(const term of terms(record.correction)){const correction=this.ensureNeuron({id:idFor('concept',term),label:term,type:'concept',strength:.45,tags:['correction']});this.adjustSynapse(agentNeuron.id,correction.id,.08,1);}this.updates+=1;return agentNeuron;}
 activate(input,{limit=18,hops=3,reinforce=true}={}){const query=terms(input);this.lastInput=String(input??'');this.applyDecay();const scores=new Map();const seeds=[];for(const term of query){const neuron=this.neurons.get(idFor('concept',term));if(neuron){const seed=1/Math.max(1,query.length);scores.set(neuron.id,(scores.get(neuron.id)??0)+seed);seeds.push(neuron);}}let frontier=seeds.map(n=>({id:n.id,score:scores.get(n.id)??0}));for(let hop=0;hop<hops;hop++){const next=[];for(const item of frontier){for(const edge of this.synapses.values()){if(edge.source!==item.id)continue;const target=this.neurons.get(edge.target);if(!target)continue;const gain=item.score*edge.weight*Math.pow(.62,hop+1);scores.set(target.id,(scores.get(target.id)??0)+gain);next.push({id:target.id,score:gain});}}frontier=next;if(!frontier.length)break;}const ranked=[...scores.entries()].map(([id,score])=>({neuron:this.neurons.get(id),score})).filter(x=>x.neuron).sort((a,b)=>b.score-a.score).slice(0,limit);for(const neuron of this.neurons.values())neuron.activation*=.72;for(const {neuron,score} of ranked){neuron.activation=clamp(score);neuron.visits+=1;neuron.lastActivatedAt=now();neuron.updatedAt=now();}this.lastTrace=ranked.map(({neuron,score})=>({id:neuron.id,label:neuron.label,type:neuron.type,activation:clamp(score)}));this.activations.push({timestamp:now(),input:this.lastInput,trace:this.lastTrace});if(this.activations.length>200)this.activations.shift();if(reinforce&&seeds.length>1)for(let i=0;i<seeds.length;i++)for(let j=i+1;j<seeds.length;j++)this.adjustSynapse(seeds[i].id,seeds[j].id,this.learningRate*.08,.25);return this.lastTrace;}
 predict(input){const trace=this.activate(input,{limit:28,hops:3,reinforce:true});const agents=trace.filter(n=>n.type==='agent');if(!agents.length)return{agent:'general',confidence:.2,trace};const best=agents[0],second=agents[1]?.activation??0;return{agent:best.label,confidence:clamp(best.activation*(.7+.3*(best.activation-second))),trace};}
 applyDecay(){const t=Date.now(),half=this.decayHalfLifeHours*3600000;if(!half)return;for(const n of this.neurons.values()){const age=Math.max(0,t-Date.parse(n.lastActivatedAt??n.updatedAt??n.createdAt));const factor=Math.pow(.5,age/half);n.activation*=factor;n.strength=clamp(.5+(n.strength-.5)*Math.max(.35,factor));}}
 consolidate({maxWeakEdge=.055,minEvidence=1}={}){this.applyDecay();let pruned=0;for(const [id,edge] of this.synapses)if(edge.evidence<minEvidence&&edge.weight<maxWeakEdge){this.synapses.delete(id);pruned++;}for(const n of this.neurons.values())if(n.activation<.02)n.activation=0;this.trim();this.updates+=pruned+1;return{pruned,stats:this.stats()};}
 snapshot({limit=100}={}){const neurons=[...this.neurons.values()].sort((a,b)=>(b.activation-a.activation)||(b.strength-a.strength)).slice(0,limit);const ids=new Set(neurons.map(n=>n.id));const synapses=[...this.synapses.values()].filter(e=>ids.has(e.source)&&ids.has(e.target)).sort((a,b)=>b.weight-a.weight).slice(0,Math.min(this.maxSynapses,limit*4));return{neurons:neurons.map(n=>({...n})),synapses:synapses.map(e=>({...e})),trace:this.lastTrace.map(x=>({...x})),lastInput:this.lastInput,updates:this.updates};}
 stats(){return{neurons:this.neurons.size,synapses:this.synapses.size,activations:this.activations.length,updates:this.updates,active:[...this.neurons.values()].filter(n=>n.activation>.18).length,concepts:[...this.neurons.values()].filter(n=>n.type==='concept').length,memories:[...this.neurons.values()].filter(n=>n.type==='memory').length,agents:[...this.neurons.values()].filter(n=>n.type==='agent').length};}
 exportState(){return{version:3,neurons:[...this.neurons.values()],synapses:[...this.synapses.values()],activations:this.activations.slice(-200),updates:this.updates};}
 importState(state){this.neurons.clear();this.synapses.clear();for(const n of Array.isArray(state?.neurons)?state.neurons:[])this.neurons.set(n.id,{...n});for(const e of Array.isArray(state?.synapses)?state.synapses:[])this.synapses.set(e.id,{...e,weight:clamp(e.weight,.02,.95),evidence:Math.max(0,Number(e.evidence)||0)});this.activations=Array.isArray(state?.activations)?state.activations.slice(-200):[];this.updates=Number(state?.updates??0);this.trim();return this.stats();}
 trim(){while(this.neurons.size>this.maxNeurons){const victim=[...this.neurons.values()].sort((a,b)=>(a.activation+a.strength)-(b.activation+b.strength))[0];if(!victim)break;this.neurons.delete(victim.id);for(const [key,e] of this.synapses)if(e.source===victim.id||e.target===victim.id)this.synapses.delete(key);}while(this.synapses.size>this.maxSynapses){const victim=[...this.synapses.values()].sort((a,b)=>a.weight-b.weight)[0];if(!victim)break;this.synapses.delete(victim.id);}}
}
