const STORAGE_KEY='wulan-local-v2';

export class WulanPersistence{
 constructor({storage,key=STORAGE_KEY}={}){this.storage=storage??(typeof globalThis!=='undefined'?globalThis.localStorage:null);this.key=key;}
 available(){return Boolean(this.storage&&typeof this.storage.getItem==='function'&&typeof this.storage.setItem==='function');}
 load(){if(!this.available())return null;try{const raw=this.storage.getItem(this.key);if(!raw)return null;const parsed=JSON.parse(raw);if(!parsed||![1,3,4,5].includes(parsed.version)||!Array.isArray(parsed.memories))return null;return parsed;}catch{return null;}}
 save(input={}){if(!this.available())return false;try{const core=input?.core;const orchestrator=core?.taskOrchestrator??core?.cognition?.orchestrator;const supervisor=core?.agentSupervisor;const payload=core?{version:5,savedAt:new Date().toISOString(),memories:core.memory?.list?.({limit:core.memory.maxEntries??5000})??[],learning:core.learning?.recent?.(5000)??[],neural:core.neural?.exportState?.()??null,semantic:core.semantic?.exportState?.()??null,tasks:orchestrator?.recent?.(100)??[],teamRuns:supervisor?.recentTeams?.(100)??[]}:{version:5,savedAt:new Date().toISOString(),memories:Array.isArray(input.memories)?input.memories:[],learning:Array.isArray(input.learning)?input.learning:[],neural:input.neural??null,semantic:input.semantic??null,tasks:Array.isArray(input.tasks)?input.tasks:[],teamRuns:Array.isArray(input.teamRuns)?input.teamRuns:[]};this.storage.setItem(this.key,JSON.stringify(payload));return true;}catch{return false;}}
 saveCore(core){return this.save({core});}
 clear(){if(!this.available())return false;try{this.storage.removeItem(this.key);return true;}catch{return false;}}
}

export function hydrateMemoryStore(memory,persistence){const snapshot=persistence?.load?.();if(!snapshot?.memories?.length)return 0;let restored=0;for(const entry of snapshot.memories){try{memory.add(entry);restored++;}catch{}}return restored;}
export function restorePersistentState(core,persistence){const snapshot=persistence?.load?.();if(!snapshot)return{learning:0,neural:false,semantic:false,tasks:0,teamRuns:0};let learning=0;for(const record of Array.isArray(snapshot.learning)?snapshot.learning:[]){try{core.learning?.record(record);learning++;}catch{}}let neural=false,semantic=false;if(snapshot.neural&&typeof core.neural?.importState==='function'){try{core.neural.importState(snapshot.neural);neural=true;}catch{}}if(snapshot.semantic&&typeof core.semantic?.importState==='function'){try{core.semantic.importState(snapshot.semantic);semantic=true;}catch{}}return{learning,neural,semantic,tasks:Array.isArray(snapshot.tasks)?snapshot.tasks.length:0,teamRuns:Array.isArray(snapshot.teamRuns)?snapshot.teamRuns.length:0};}
export function persistMemoryStore(memory,persistence){if(!persistence?.save)return false;return persistence.save({memories:memory.list({limit:memory.maxEntries??5000})});}