/** Browser-safe Gemini adapter. The API key stays server-side. */
const ENDPOINT='/api/gemini', EMBED_ENDPOINT='/api/gemini-embed', MODEL='gemini-2.5-flash', TIMEOUT_MS=30000;
let _callCount=0,_lastCallAt=null,_lastResponseMs=null,_lastSuccessAt=null,_lastFailAt=null,_lastFailMsg=null,_lastStatus=null,_lastTokensIn=null,_lastTokensOut=null;
export function getGeminiStats(){return{model:MODEL,endpoint:ENDPOINT,callCount:_callCount,lastCallAt:_lastCallAt,lastResponseMs:_lastResponseMs,lastSuccessAt:_lastSuccessAt,lastFailAt:_lastFailAt,lastFailMsg:_lastFailMsg,lastStatus:_lastStatus,lastTokensIn:_lastTokensIn,lastTokensOut:_lastTokensOut};}
export function resetGeminiStats(){_callCount=0;_lastCallAt=null;_lastResponseMs=null;_lastSuccessAt=null;_lastFailAt=null;_lastFailMsg=null;_lastStatus=null;_lastTokensIn=null;_lastTokensOut=null;}
export function hasGeminiKey(){return true;}
async function postJson(endpoint,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error||`HTTP ${res.status}`);return data;}catch(error){throw error?.name==='AbortError'?new Error('TIMEOUT'):error;}finally{clearTimeout(timer);}}
export async function callGemini(messages,system='',source='chat'){_callCount++;_lastCallAt=new Date().toISOString();const started=Date.now();try{const data=await postJson(ENDPOINT,{messages,system,source});const text=data?.text?.trim();if(!text)throw new Error('EMPTY_RESPONSE');_lastStatus=200;_lastResponseMs=Date.now()-started;_lastSuccessAt=new Date().toISOString();_lastTokensIn=data?.usage?.promptTokenCount??null;_lastTokensOut=data?.usage?.candidatesTokenCount??null;return text;}catch(error){_lastResponseMs=Date.now()-started;_lastFailAt=new Date().toISOString();_lastFailMsg=String(error?.message||error);_lastStatus=error?.message?.startsWith('HTTP ')?Number(error.message.slice(5)):null;throw error;}}
export async function embedGemini(text){const value=String(text??'').trim();if(!value)throw new Error('EMPTY_EMBEDDING_INPUT');const data=await postJson(EMBED_ENDPOINT,{text:value});if(!Array.isArray(data?.values)||!data.values.length)throw new Error('EMPTY_EMBEDDING');return data.values;}
