const STYLE=`#wulan-neural-field .nf-canvas{opacity:0}#wulan-neural-field .nf-organized{position:absolute;inset:0;width:100%;height:100%;cursor:crosshair}#wulan-neural-field .nf-help{right:18px;bottom:18px}#wulan-neural-field .nf-inspect{z-index:5}`;
(()=>{
 const boot=()=>{
  const core=globalThis.WULAN_CORE,root=document.getElementById('wulan-neural-field');
  if(!core||!root||root.dataset.organized==='1')return false;
  root.dataset.organized='1';const s=document.createElement('style');s.textContent=STYLE;document.head.appendChild(s);
  const old=root.querySelector('.nf-canvas'),panel=root.querySelector('.nf-panel'),inspect=root.querySelector('#nf-inspect');
  const canvas=document.createElement('canvas');canvas.className='nf-organized';panel.insertBefore(canvas,root.querySelector('.nf-stats'));
  const ctx=canvas.getContext('2d'),nodes=[],pointer={x:0,y:0,active:false};let edges=[],selected=null,dragging=null,w=0,h=0,dpr=1,t=0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const color=n=>n.type==='system'?'#a98bff':n.type==='agent'?'#e7c36c':n.type==='memory'?'#70e5b4':n.type==='concept'?'#79e8ff':'#8fa9c4';
  const hash=x=>{let h=0;for(let i=0;i<x.length;i++)h=((h<<5)-h+x.charCodeAt(i))|0;return Math.abs(h)};
  const resize=()=>{const r=panel.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);layout()};
  function ring(arr,r,start){const max=10;if(!arr.length)return;for(let k=0;k<Math.ceil(arr.length/max);k++){const part=arr.slice(k*max,(k+1)*max),rr=r*(.78+k*.34);part.forEach((n,i)=>{const a=start+i/part.length*Math.PI*2+(k%2)*.13;n.x=w/2+Math.cos(a)*rr;n.y=h/2+Math.sin(a)*rr*.62})}}
  function layout(){const snap=core.neural.snapshot({limit:96});nodes.length=0;const g={system:[],agent:[],memory:[],concept:[],other:[]};snap.neurons.forEach(n=>(g[n.type]||g.other).push({...n}));g.system.forEach(n=>{n.x=w/2;n.y=h/2;nodes.push(n)});const m=Math.min(w,h);ring(g.agent,m*.15,-Math.PI/2);ring(g.memory,m*.27,-Math.PI/2+.35);ring(g.concept,m*.39,-Math.PI/2-.12);ring(g.other,m*.47,-Math.PI/2+.7);nodes.push(...g.agent,...g.memory,...g.concept,...g.other);const map=new Map(nodes.map(n=>[n.id,n]));edges=snap.synapses.map(e=>({...e,a:map.get(e.source),b:map.get(e.target)})).filter(e=>e.a&&e.b);updateStats()}
  function updateStats(){const s=core.neural.stats();['neurons','synapses','active','updates'].forEach(k=>{const el=root.querySelector('#nf-'+k);if(el)el.textContent=s[k]})}
  function edge(e){const a=e.a,b=e.b,active=a.activation>.1||b.activation>.1||selected&&(selected.id===a.id||selected.id===b.id),mute=selected&&!active;const mx=(a.x+b.x)/2,my=(a.y+b.y)/2,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,bend=(hash(a.id+b.id)%41)-20,cx=mx+(w/2-mx)*.14-dy/len*bend,cy=my+(h/2-my)*.14+dx/len*bend;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(cx,cy,b.x,b.y);ctx.strokeStyle=active?`rgba(121,232,255,${.28+e.weight*.55})`:mute?'rgba(110,150,180,.015)':`rgba(125,170,205,${.025+e.weight*.10})`;ctx.lineWidth=active?1.6:Math.max(.3,e.weight*.7);if(active){ctx.setLineDash([4,8]);ctx.lineDashOffset=-t*18}ctx.stroke();ctx.setLineDash([])}
  function node(n){const active=n.activation>.1||selected?.id===n.id,focused=!selected||active||edges.some(e=>active&&(e.a.id===n.id||e.b.id===n.id)),r=(n.type==='system'?7:4)+n.strength*5+(active?n.activation*7:0),c=color(n);ctx.globalAlpha=focused?1:.2;if(active){ctx.beginPath();ctx.arc(n.x,n.y,r*3,0,Math.PI*2);ctx.fillStyle='rgba(121,232,255,.07)';ctx.fill()}ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);ctx.fillStyle='#06101a';ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=active?1.8:1;ctx.stroke();ctx.globalAlpha=1;if(active||n.type==='agent'||n.type==='memory'||n.type==='system'){const label=n.type==='system'?'WULAN CORE':String(n.label).slice(0,22);ctx.font='500 7px ui-monospace,monospace';const tw=ctx.measureText(label).width+10,y=n.y+r+15;ctx.fillStyle='rgba(2,8,14,.76)';ctx.beginPath();ctx.roundRect(n.x-tw/2,y-8,tw,14,5);ctx.fill();ctx.fillStyle='rgba(225,241,255,.82)';ctx.textAlign='center';ctx.fillText(label,n.x,y+1)}}
  function draw(){ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,Math.min(w,h)*.62);bg.addColorStop(0,'rgba(65,145,190,.12)');bg.addColorStop(.55,'rgba(49,74,130,.035)');bg.addColorStop(1,'transparent');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const m=Math.min(w,h);[.15,.27,.39,.47].forEach(r=>{ctx.beginPath();ctx.ellipse(w/2,h/2,m*r,m*r*.62,0,0,Math.PI*2);ctx.strokeStyle='rgba(121,232,255,.04)';ctx.stroke()});edges.forEach(edge);nodes.forEach(node);if(pointer.active){ctx.beginPath();ctx.arc(pointer.x,pointer.y,13+Math.sin(t)*2,0,Math.PI*2);ctx.strokeStyle='rgba(121,232,255,.12)';ctx.stroke()}t+=.035;requestAnimationFrame(draw)}
  function nearest(x,y){let best=null,d=1e9;for(const n of nodes){const q=Math.hypot(n.x-x,n.y-y);if(q<d){d=q;best=n}}return d<30?best:null}
  function inspectNode(n){selected=n;const links=edges.filter(e=>e.a.id===n.id||e.b.id===n.id);inspect.classList.add('show');inspect.innerHTML=`<b>${esc(n.type==='system'?'WULAN CORE':n.label)}</b><small>${esc(n.type)} · strength ${Math.round(n.strength*100)}% · activation ${Math.round(n.activation*100)}% · visits ${n.visits}<br>${links.length} connected synapses · ${(n.tags||[]).map(esc).join(' · ')||'no tags'}</small>`}
  canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top;pointer.active=true;if(dragging){dragging.x=pointer.x;dragging.y=pointer.y}canvas.style.cursor=nearest(pointer.x,pointer.y)?'pointer':'crosshair'});
  canvas.addEventListener('pointerleave',()=>pointer.active=false);canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),n=nearest(e.clientX-r.left,e.clientY-r.top);if(n){dragging=n;inspectNode(n);canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointerup',e=>{dragging=null;try{canvas.releasePointerCapture(e.pointerId)}catch{}});
  canvas.addEventListener('dblclick',e=>{const r=canvas.getBoundingClientRect(),n=nearest(e.clientX-r.left,e.clientY-r.top);if(n){core.neural.activate(n.label);layout();inspectNode(n)}});
  core.events.on('memory.created',()=>{if(root.classList.contains('open'))layout()});core.events.on('neural.updated',()=>{if(root.classList.contains('open'))layout()});core.events.on('neural.activated',()=>{if(root.classList.contains('open'))layout()});
  old.style.display='none';window.addEventListener('resize',resize);resize();draw();return true;
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{const timer=setInterval(()=>{if(boot())clearInterval(timer)},100),{once:true});else{const timer=setInterval(()=>{if(boot())clearInterval(timer)},100)}
})();